In [1]:
pip install wordcloud

Requirement already satisfied: wordcloud in c:\anaconda file\lib\site-packages (1.9.6)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.19.3 in c:\anaconda file\lib\site-packages (from wordcloud) (1.26.4)
Requirement already satisfied: pillow in c:\anaconda file\lib\site-packages (from wordcloud) (10.4.0)
Requirement already satisfied: matplotlib in c:\anaconda file\lib\site-packages (from wordcloud) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\anaconda file\lib\site-packages (from matplotlib->wordcloud) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\anaconda file\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\anaconda file\lib\site-packages (from matplotlib->wordcloud) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\anaconda file\lib\site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\anaconda file\lib\site-packages (from matplotlib->wordcloud) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\anaconda file\lib\site-packages (from matplotlib->wordcloud) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\anaconda file\lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\anaconda file\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from wordcloud import WordCloud

import nltk 
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
df=pd.read_csv('spam.csv')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [7]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.rename(columns={'v1':'target','v2':'text'},inplace=True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

## Data PrePocessing

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['target']=encoder.fit_transform(df['target'])
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [13]:
len(df)-df.duplicated().sum()

5169

In [14]:
len(df)

5572

In [16]:
df.drop_duplicates(keep='first',inplace=True)
len(df)

5169

## Data cleaning

In [17]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [18]:
import string

In [21]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [24]:
def transform_text(text):
    #lowering text
    text=text.lower()

    #tokeninzing text so we get individual words instead of whole string
    text=nltk.word_tokenize(text)

    #creating list that will store all the updated words which we will pass back to text
    y=[]

    #Removing punctuation using isalnum() function and passing all the words to y
    for i in text:
        if i.isalnum():
            y.append(i)
    text=y[:]
    y.clear()

    #removing stopwords(words like is,the,this) passing leftover to y and then to text
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text=y[:]
    y.clear()

    #steming i.e making similar words as same token
    for i in text:
        y.append(ps.stem(i))

    #returning the transformed text but in string format instead of tokens
    return ' '.join(y)

In [ ]:
#testing out the function 
t=transform_text('Does this work like i need it to work')
print(t)

work like need worker

In [28]:
df['transformed_text']=df['text'].apply(transform_text)
df.head()

,target,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

## Feature engineering

In [29]:
#Turning text into numeric form i.e weights for each unique word using tfidvectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
X=tf.fit_transform(df['transformed_text']).toarray()
y=df['target'].values

## Train_test_split

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

## Model training

In [35]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\anaconda file\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\anaconda file\lib\site-packages (from xgboost) (1.13.1)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
   ---------------------------------------- 0.5/48.9 MB 119.9 kB/s eta 0:06:44
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 0.8/48.9 MB 64.7 kB/s eta 0:12:25
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
    --------------------------------------- 1.0/48.9 MB 58.0 kB/s eta 0:13:46
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.3/48.9 MB 58.1 kB/s eta 0:13:40
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.6/48.9 MB 57.7 kB/s eta 0:13:42
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 1.8/48.9 MB 58.0 kB/s eta 0:13:33
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.1/48.9 MB 56.5 kB/s eta 0:13:49
   - -------------------------------------- 2.4/48.9 MB 61.2 kB/s eta 0:12:41
   - -------------------------------------- 2.4/48.9 MB 61.2 kB/s eta 0:12:41
   - -------------------------------------- 2.4/48.9 MB 61.2 kB/s eta 0:12:41
   - -------------------------------------- 2.4/48.9 MB 61.2 kB/s eta 0:12:41
   - -------------------------------------- 2.4/48.9 MB 61.2 kB/s eta 0:12:41
   - -------------------------------------- 2.4/48.9 MB 61.2 kB/s eta 0:12:41
   - -------------------------------------- 2.4/48.9 MB 61.2 kB/s eta 0:12:41
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.6/48.9 MB 72.0 kB/s eta 0:10:44
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 2.9/48.9 MB 77.1 kB/s eta 0:09:58
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.1/48.9 MB 79.8 kB/s eta 0:09:35
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.4/48.9 MB 90.7 kB/s eta 0:08:23
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   -- ------------------------------------- 3.7/48.9 MB 94.0 kB/s eta 0:08:02
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 3.9/48.9 MB 96.6 kB/s eta 0:07:47
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.2/48.9 MB 106.9 kB/s eta 0:06:59
   --- ------------------------------------ 4.5/48.9 MB 109.4 kB/s eta 0:06:47
   --- ------------------------------------ 4.5/48.9 MB 109.4 kB/s eta 0:06:47
   --- ------------------------------------ 4.5/48.9 MB 109.4 kB/s eta 0:06:47
   --- ------------------------------------ 4.5/48.9 MB 109.4 kB/s eta 0:06:47
   --- ------------------------------------ 4.5/48.9 MB 109.4 kB/s eta 0:06:47
   --- ------------------------------------ 4.5/48.9 MB 109.4 kB/s eta 0:06:47
   --- ------------------------------------ 4.7/48.9 MB 123.8 kB/s eta 0:05:58
   --- ------------------------------------ 4.7/48.9 MB 123.8 kB/s eta 0:05:58
   --- ------------------------------------ 4.7/48.9 MB 123.8 kB/s eta 0:05:58
   --- ------------------------------------ 4.7/48.9 MB 123.8 kB/s eta 0:05:58
   --- ------------------------------------ 4.7/48.9 MB 123.8 kB/s eta 0:05:58
   ---- ----------------------------------- 5.0/48.9 MB 129.3 kB/s eta 0:05:41
   ---- ----------------------------------- 5.0/48.9 MB 129.3 kB/s eta 0:05:41
   ---- ----------------------------------- 5.0/48.9 MB 129.3 kB/s eta 0:05:41
   ---- ----------------------------------- 5.2/48.9 MB 135.6 kB/s eta 0:05:23
   ---- ----------------------------------- 5.2/48.9 MB 135.6 kB/s eta 0:05:23
   ---- ----------------------------------- 5.2/48.9 MB 135.6 kB/s eta 0:05:23
   ---- ----------------------------------- 5.5/48.9 MB 142.4 kB/s eta 0:05:05
   ---- ----------------------------------- 5.5/48.9 MB 142.4 kB/s eta 0:05:05
   ---- ----------------------------------- 5.8/48.9 MB 149.5 kB/s eta 0:04:49
   ---- ----------------------------------- 5.8/48.9 MB 149.5 kB/s eta 0:04:49
   ---- ----------------------------------- 6.0/48.9 MB 156.8 kB/s eta 0:04:34
   ----- ---------------------------------- 6.3/48.9 MB 164.2 kB/s eta 0:04:20
   ----- ---------------------------------- 6.6/48.9 MB 171.6 kB/s eta 0:04:08
   ----- ---------------------------------- 6.6/48.9 MB 171.6 kB/s eta 0:04:08

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [37]:
svc = SVC(kernel= "sigmoid", gamma  = 1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth = 5)
lrc = LogisticRegression(solver = 'liblinear', penalty = 'l1')
rfc = RandomForestClassifier(n_estimators = 50, random_state = 2 )
abc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
gbdt = GradientBoostingClassifier(n_estimators = 50, random_state = 2)    
xgb  = XGBClassifier(n_estimators = 50, random_state = 2)

In [ ]:
clfs = {
    'SVC': svc,
    'KNN': knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'Adaboost': abc,
    'Bgc': bc,
    'ETC': etc,
    'GBDT': gbdt,
    'xgb': xgb
    
}

## Model Evaluation

In [39]:
from sklearn.metrics import accuracy_score, precision_score
def train_classifier(clfs, X_train, y_train, X_test, y_test):
    clfs.fit(X_train,y_train)
    y_pred = clfs.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    return accuracy , precision

In [40]:
accuracy_scores = []
precision_scores = []
for name , clfs in clfs.items():
    current_accuracy, current_precision = train_classifier(clfs, X_train, y_train, X_test, y_test)
    print()
    print("For: ", name)
    print("Accuracy: ", current_accuracy)
    print("Precision: ", current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For:  SVC
Accuracy:  0.9729206963249516
Precision:  0.9741379310344828

c:\Anaconda file\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Anaconda file\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Anaconda file\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Anaconda file\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Anaconda file\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For:  KNN
Accuracy:  0.9003868471953579
Precision:  1.0

For:  NB
Accuracy:  0.9593810444874274
Precision:  1.0

For:  DT
Accuracy:  0.9361702127659575
Precision:  0.8461538461538461

For:  LR
Accuracy:  0.9516441005802708
Precision:  0.94

For:  RF
Accuracy:  0.971953578336557
Precision:  1.0

c:\Anaconda file\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

For:  Adaboost
Accuracy:  0.9613152804642167
Precision:  0.9454545454545454

For:  Bgc
Accuracy:  0.9584139264990329
Precision:  0.8625954198473282

For:  ETC
Accuracy:  0.9729206963249516
Precision:  0.9824561403508771

For:  GBDT
Accuracy:  0.9526112185686654
Precision:  0.9238095238095239

For:  xgb
Accuracy:  0.9709864603481625
Precision:  0.9426229508196722